### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by juanmiconlup** [Clanify/Clanify#1]
Can you explain how to install at readme file please?

**Comment by sebastianbrosch** [comment]
At the moment the development is not finished but I can commit everything (at the moment the views are missing on repository) and describe the installation.

**Comment by sebastianbrosch** [comment]
I described the installation on README.md. If you still need support, you can send me a mail to support@clanify.rocks.

**Hint:** At the moment Clanify is only a development version.
